name: yuyan_app

description: 语燕，一款第三方语雀移动客户端

version: 1.1.1+1.1.1

environment:
  sdk: ">=2.10.0 <3.0.0"

publish_to: none

dependency_overrides:
  crypto: ^3.0.1
  url_launcher: ^6.0.16

dependencies:
  badges: ^1.1.0
  bot_toast: ^4.0.1
  cached_network_image: ^2.0.0
  chewie: ^1.0.0
  clipboard: 0.1.2+8
  curved_navigation_bar: ^0.4.0-nullsafety.0
  delta_markdown: ^0.3.0
  dio: 4.0.0-beta7
  extended_image: 3.0.0
  extended_nested_scroll_view: 3.0.0
  firebase_analytics: ^8.3.4
  firebase_core: ^1.10.0
  flare_flutter: ^3.0.0
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^1.1.0
  flutter_highlight: 0.6.0
  flutter_html:
    git:
      ref: 47e3931596dc4bb1d5f6e6a38d829e91e54d9abb
      url: https://github.com/vrtdev/flutter_html.git
  flutter_inappwebview: ^5.2.1+1
  flutter_markdown: ^0.6.1
  flutter_quill: ^2.0.22
  flutter_simple_treeview: 2.0.2
  flutter_staggered_animations: 1.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_swiper: 1.1.6
  flutter_webview_plugin:
    git: https://github.com/aboutmydreams/flutter_webview_plugin.git
  flutter_xupdate: ^1.0.2
  fluttertoast: ^3.1.3
  font_awesome_flutter: ^8.7.0
  get: 4.0.0-nullsafety.2
  get_storage: 2.0.1
  html2md: ^1.0.1
  image_picker: ^0.8.2
  liquid_swipe: ^1.5.0
  notus: 1.0.0-dev.4.0
  package_info: ^0.4.3+2
  path_provider: ^2.0.1
  permission_handler: ^6.1.1
  photo_view: ^0.13.0
  pretty_json: 1.1.0
  pull_to_refresh: ^2.0.0
  recase: 3.0.1
  romanice: 1.0.0+1
  scroll_to_index: 1.0.6
  share_extend: ^1.1.9
  shared_preferences: ^2.0.5
  shifting_tabbar: ^1.0.2
  sliding_up_panel: ^1.0.1
  smart_color: ^0.2.2
  tuple: 2.0.0
  url_launcher: ^6.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/js/
    - assets/flares/
    - assets/images/
    - assets/images/guide/
    - assets/images/explore/
    - assets/images/dashboard/
    - assets/images/news/
    - assets/images/my_page/
    - assets/images/card/

  fonts:
    - family: Silom
      fonts:
        - asset: assets/fonts/Silom.ttf
    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
